version: '3.3'

services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    # container_name: mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    tmpfs:
      - /var/lib/mysql
