version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-pipdevs/test}
    depends_on:
      - kafka
    environment:
      - KAFKA_SERVICE_PORT=9092
      - KAFKA_SERVICE_HOST=kafka
      - KAFKA_QUEUE=test

  kafka:
    image: 'bitnami/kafka:latest'
    # ports:
    #   - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    # ports:
    #   - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes