// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/commandable.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace PipServices4.Grpc.Services {
  /// <summary>
  /// The commandable service definition.
  /// </summary>
  public static partial class Commandable
  {
    static readonly string __ServiceName = "commandable.Commandable";

    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    static readonly grpc::Marshaller<global::PipServices4.Grpc.Services.InvokeRequest> __Marshaller_commandable_InvokeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PipServices4.Grpc.Services.InvokeRequest.Parser));
    static readonly grpc::Marshaller<global::PipServices4.Grpc.Services.InvokeReply> __Marshaller_commandable_InvokeReply = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::PipServices4.Grpc.Services.InvokeReply.Parser));

    static readonly grpc::Method<global::PipServices4.Grpc.Services.InvokeRequest, global::PipServices4.Grpc.Services.InvokeReply> __Method_invoke = new grpc::Method<global::PipServices4.Grpc.Services.InvokeRequest, global::PipServices4.Grpc.Services.InvokeReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "invoke",
        __Marshaller_commandable_InvokeRequest,
        __Marshaller_commandable_InvokeReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::PipServices4.Grpc.Services.CommandableReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Commandable</summary>
    [grpc::BindServiceMethod(typeof(Commandable), "BindService")]
    public abstract partial class CommandableBase
    {
      public virtual global::System.Threading.Tasks.Task<global::PipServices4.Grpc.Services.InvokeReply> invoke(global::PipServices4.Grpc.Services.InvokeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Commandable</summary>
    public partial class CommandableClient : grpc::ClientBase<CommandableClient>
    {
      /// <summary>Creates a new client for Commandable</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CommandableClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Commandable that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CommandableClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CommandableClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CommandableClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::PipServices4.Grpc.Services.InvokeReply invoke(global::PipServices4.Grpc.Services.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return invoke(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::PipServices4.Grpc.Services.InvokeReply invoke(global::PipServices4.Grpc.Services.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_invoke, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::PipServices4.Grpc.Services.InvokeReply> invokeAsync(global::PipServices4.Grpc.Services.InvokeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return invokeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::PipServices4.Grpc.Services.InvokeReply> invokeAsync(global::PipServices4.Grpc.Services.InvokeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_invoke, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CommandableClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CommandableClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CommandableBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_invoke, serviceImpl.invoke).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CommandableBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_invoke, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::PipServices4.Grpc.Services.InvokeRequest, global::PipServices4.Grpc.Services.InvokeReply>(serviceImpl.invoke));
    }

  }
}
#endregion
